on:
  rss:
    url:
      - https://rsshub.app/gcores/category/articles
      - https://rsshub.app/guokr/scientific
      - https://rsshub.app/sciencenet/blog
      - https://rsshub.app/sspai/index
      - https://rsshub.app/chaoli/sci-fi
      - https://rsshub.app/chaoli/tech
      - https://rsshub.app/chaoli/physics
      - https://rsshub.app/dailyart/zh
      - https://rsshub.app/smzdm/haowen/1
      - https://rsshub.app/mubu/explore/16/%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0
      - https://rsshub.app/bilibili/user/video/1119961064
      - https://rsshub.app/bilibili/user/video/314022607
      - https://rsshub.app/bilibili/user/video/432408734
      - https://rsshub.app/bilibili/user/video/402780815
      - https://rsshub.app/bilibili/user/video/38294246
      - https://rsshub.app/bilibili/user/video/29959830
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.CUBOXAPI }}
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}",
              "title": "${{ on.rss.outputs.title }}",
              "tags":["api"],
              "folder":"apifeeds"
            }
